const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`
const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`
const TODOS_FILTER_PROGRESS = `TODOS_FILTER_PROGRESS`


export {TODOS_FILTER_ALL, TODOS_FILTER_COMPLETED, TODOS_FILTER_PROGRESS}